<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>prog_par1</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="WhatsApp Ptt 2026-08-19 at 12.43.50.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="WhatsApp Ptt 2026-08-19 at 12.43.50.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Windows.Extensions" Version="10.0.11" />
  </ItemGroup>

</Project>
